# Generated by Django 2.2.6 on 2019-10-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='imgage',
        ),
        migrations.AddField(
            model_name='profile',
            name='imaage',
            field=models.ImageField(default='efault.jpg', upload_to='profile_pics'),
        ),
    ]
