# Generated by Django 2.2.6 on 2019-10-10 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(default='', max_length=128)),
                ('live', models.CharField(default='', max_length=128)),
                ('land', models.CharField(default='', max_length=128)),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('birthdate', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='enabled',
        ),
        migrations.AddField(
            model_name='cronjob',
            name='authentification',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='password',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='username',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
