# Generated by Django 2.2.6 on 2019-10-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronjob',
            name='password',
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='username',
        ),
    ]
