# Generated by Django 2.2.6 on 2019-10-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20191010_1628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testjob',
            new_name='Friend',
        ),
    ]
