# Generated by Django 2.2.6 on 2019-10-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20191008_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronjob',
            name='enabled',
        ),
        migrations.AddField(
            model_name='cronjob',
            name='auswahl',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
