# Generated by Django 2.2.6 on 2019-10-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20191009_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='auswahl',
            field=models.IntegerField(default=''),
        ),
    ]
