# Generated by Django 2.2.6 on 2019-10-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20191010_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='live',
            new_name='lives',
        ),
    ]
