# Generated by Django 2.2.6 on 2019-10-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20191009_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('url', models.URLField(default='', max_length=255)),
            ],
        ),
    ]
