# Generated by Django 2.2.6 on 2019-10-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_testjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronjob',
            name='auswahl',
        ),
    ]
