# Generated by Django 2.2.6 on 2019-10-09 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_remove_cronjob_auswahl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='password',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='username',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
