# Generated by Django 2.2.6 on 2019-10-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20191011_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='cronjob',
            field=models.CharField(default='*****', max_length=5),
        ),
    ]
