# Generated by Django 2.2.6 on 2019-10-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_cronjob_cronjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='day',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='hour',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='minute',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
