# Generated by Django 2.2.6 on 2019-10-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20191009_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='authentification',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
