# Generated by Django 2.2.6 on 2019-10-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_auto_20191009_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='day',
            field=models.PositiveSmallIntegerField(default=0, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='hour',
            field=models.PositiveSmallIntegerField(default=0, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='minute',
            field=models.PositiveSmallIntegerField(default=0, max_length=60, null=True),
        ),
    ]
