# Generated by Django 2.2.6 on 2019-10-11 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_auto_20191011_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
